language: python
dist: xenial

python:
  - 3.5
  - 3.6
  - 3.7

install: pip install tox

# http://stackoverflow.com/a/42309035
script:
  - tox --recreate -e $(echo py${TRAVIS_PYTHON_VERSION} | tr -d . | sed -e 's/pypypy/pypy/') lint

deploy:
  provider: pypi
  user: n8henrie
  password:
    secure: axvmJF5WeLLaTy9oTOHPrnM5NQT5FC3Ef1+taIuIHa+BclN6JRbz7wUd/GdcAVwzEWv9Gaq4Au/sLMjgXgb+9bJ+pjZHAns4yVxjhDY46bX4OkRsrZvvrC3dpUGmmFAmKyVlB77DO9sVXu5CQjZtX/vVvEamAbAzbUdzWzwI630=
  distributions: sdist bdist_wheel
  on:
    branch: master
    tags: true
